spring:
  profiles:
    active: dev
  application:
    name: zuul
  
server: 
  port: 8088
  tomcat:
      uri-encoding: UTF-8
    
logging:
  config: classpath:logback-boot.xml
  path: /project/logs/microservice-springcloud/zuul    
    
---
spring:
  profiles: dev
 
eureka: 
  client: 
    service-url: 
      defaultZone: http://127.0.0.1:7001/eureka/
  instance:
    instance-id: zuul-01
    prefer-ip-address: true

zuul: 
  #prefix: /vtg
  ignored-services: "*"
  routes: 
    provider-dept: /dept/**
    
---
spring:
  profiles: test
 
eureka: 
  client: 
    service-url: 
      defaultZone: http://127.0.0.1:7001/eureka/
  instance:
    instance-id: zuul-01
    prefer-ip-address: true